# ── Stage 1: Install dependencies ─────────────────────────────────────
FROM node:22-alpine AS deps
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts

# ── Stage 2: Build the application ───────────────────────────────────
FROM node:22-alpine AS builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Next.js collects anonymous telemetry — disable in CI / Docker builds
ENV NEXT_TELEMETRY_DISABLED=1

RUN npm run build

# ── Stage 3: Production runner ───────────────────────────────────────
FROM node:22-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Don't run as root
RUN addgroup --system --gid 1001 nodejs && \
    adduser  --system --uid 1001 nextjs

# Copy standalone server output
COPY --from=builder /app/.next/standalone ./
# Copy static assets generated by Next.js
COPY --from=builder /app/.next/static ./.next/static

# Next.js standalone builds hardcode trustHostHeader to false for non-Vercel
# deployments (build/index.js). Patch it so the server trusts the Host header
# from the reverse proxy instead of using the internal bind address for URL
# construction and routing. This is required for Cloudflare Tunnel / Nginx etc.
RUN sed -i 's/"trustHostHeader":false/"trustHostHeader":true/g' server.js

# Create storage directory for uploaded files (mounted as volume in production)
RUN mkdir -p /app/storage && chown nextjs:nodejs /app/storage

USER nextjs

EXPOSE 3000
ENV PORT=3000
# Bind to all interfaces so the container is reachable from the Docker network.
ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js"]
